### PR TITLE
[ISSUE #4109 ] Code Optimization.[ClientGroupWrapper]

### LINKED ISSUE #4109: [Enhancement] Do some code optimization.[ClientGroupWrapper]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

image
image
image
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/group/ClientGroupWrapper.java line 91-101,112,141,220,269,335,362,391,417

### Describe the solution you'd like

image
image

restore interrupted state:
image

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by nitheesh-daram**
Fixes #4109 

### Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
- If a feature is not applicable for documentation, explain why?
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Review by Alonexc — COMMENTED** [review]
The issue description requires the `fianl` modifier to be added to the attribute.

**Comment by nitheesh-daram** [comment]
> The issue description requires the `fianl` modifier to be added to the attribute. and please check checkstyle.

Made the code review changes

**Review by Alonexc — APPROVED** [review]
LGTM

**Review by xwm1992 — APPROVED** [review]

**Review by lrhkobe — APPROVED** [review]
LGTM

**Pull request merged**
