### PR TITLE
[ISSUE #4963] Updating version of pinpoint libraries to 3.0.0

### LINKED ISSUE #4963: [Enhancement] Upgrade pinpoint-profiler to 3.x.x
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

Dependabot failed to upgrade com.navercorp.pinpoint:pinpoint-profiler from 2.4.1 to 2.5.4 in https://github.com/apache/eventmesh/pull/4961. The build failed because there are references to `DefaultTraceRoot` which has been removed.

### Describe the solution you'd like

Update deprecated usages. Upgrade to v3 if possible.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

### PR DESCRIPTION
**Pull request by lmnewton**
Fixes #4963

### Motivation

Upgrading version of the Pinpoint libraries to the latest version (some deprecated functionality had been removed in the 3.0.0 release so updates were necessary.

### Modifications
- Updated the libraries to 3.0.0 version of the pinpoint-profiler libraries in support of the associated trace plugin.
- Added case to unit test to validate that parent span information was passed correctly.

### Documentation

- Does this pull request introduce a new feature? No
- If yes, how is the feature documented? NA
- If a feature is not applicable for documentation, explain why? Library upgrade, no docs required.
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Review by Pil0tXia — APPROVED** [review]
LGTM, good job.

**Comment by lmnewton** [comment]
Checkstyle violations should be fixed now... Sorry about that @Pil0tXia !

**Comment by Pil0tXia** [comment]
@lmnewton Please notice CI failure~

**Comment by lmnewton** [comment]
Should be fixed now, @Pil0tXia . Thanks for your patience!

**Review by Pil0tXia — APPROVED** [review]

**Pull request merged**
