### PR TITLE
[ISSUE #4206] Add github-action 'stale' bot to this repo

### LINKED ISSUE #4206: [Feature] Add 'stale' github-action bot to this repo
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

The issues and pull requests in the eventmesh repository can be subjected to the stale mechanism, just like many other repositories that employ this bot. If an issue or pull request remains inactive for a certain period of time, it will be automatically closed.

Example of a stale issue:
23b8e82675b5a03ccc7538e371f6bc8
7223737029d5af110c4fdd8807bf458

Example of a stale pull request:
451ed006888dfda8ad0f9417b03e63f
cc0d273a9e6b5952f40a34188c155df

When the bot adds the stale label, all participants will receive a notification. The label will be automatically removed and the timer reset when there is new activity on the issue or pull request (as shown in Figure 2).

Maintainers have the ability to remove the stale label (as shown in Figure 4), and only Authors who are genuinely inactive will be affected.

Pinned issues and long-standing to-do lists should be retained.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by Pil0tXia**
Fixes #4206.

### Motivation

Please see https://github.com/apache/eventmesh/issues/4206.

If an issue or pull request remains inactive for a certain period of time, it will be automatically closed.

### Modifications

I have set up a whitelist for pull requests with the `help wanted` label and for issues with the labels `pinned`, `discussion`, `good first issue`, `Hacktoberfest` and `help wanted`.

### For Contributors

The `good first issue` list is maintained by @Alonexc . If a pull request remains inactive for an extended period, it will be closed. However, if the assignee has not even submitted the pull request, it cannot be automatically handled. This decision depends on Alonexc's preference. If maintaining it becomes too burdensome, I suggest **removing this whitelist** and adding the `help wanted` label to good first issues that have been inactive for a long time and triggered the `stale` status.

### For Maintainers

Pinned issues and to-do lists need to be labeled with the `pinned` or `discussion` or `help wanted` tag.

- [ ] https://github.com/apache/eventmesh/issues/888 **just this issue**
- [ ] All issues in https://github.com/apache/eventmesh/issues/3873

### Documentation

- Does this pull request introduce a new feature? (yes)
- If yes, how is the feature documented? (JavaDocs)
- If a feature is not applicable for documentation, explain why?
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Review by Alonexc — DISMISSED** [review]

**Comment by Pil0tXia** [comment]
@Alonexc Hello Alonexc, I noticed that not all of the good first issues were labeled `good first issue`, as a resualt the `good first issue` label added to exempt (or whitelist) will not cover all of the good first issues.

Considering this situation and comparing with the solution I mentioned which "removing this whitelist and adding the help wanted label to good first issues that have been inactive for a long time and triggered the stale status", would you think it would be better to remove the `good first issue` exempt?

**Comment by Alonexc** [comment]
Hi, I think it's OK, the tag will be marked when it's raised, and if some issues are fixed, I'll go ahead and close it too.

**Comment by Pil0tXia** [comment]
Thank you for your reply. I have removed `good first issue` and `Hacktoberfest` label exempt. You will get notified when assignees appear to be inactive.

**Comment by Pil0tXia** [comment]
My fork repo has enabled Continuous Integration, and the latest commit passed all the checks.
https://github.com/Pil0tXia/eventmesh/actions/runs/5503786654/jobs/10029334958

@xwm1992 Please add `pinned` tag for https://github.com/apache/eventmesh/issues/3873 and https://github.com/apache/eventmesh/issues/888. Thanks.

Here is the list of issues included in #3873 that are still unclaimed at this time, please add `help wanted` tag to keep them:

- [ ] https://github.com/apache/eventmesh/issues/3804
- [ ] https://github.com/apache/eventmesh/issues/3327
- [ ] https://github.com/apache/eventmesh/issues/2040
- [ ] https://github.com/apache/eventmesh/issues/2187
- [ ] https://github.com/apache/eventmesh/issues/2805
- [ ] https://github.com/apache/eventmesh/issues/676

Besides, maybe you would like to add this issue into `What are we doing now?`: https://github.com/apache/eventmesh/issues/2179

**Comment by Pil0tXia** [comment]
I added `weopen-star`, `GLCC`, `summer of code` label to the exempt. These kinds of open source events go on for a long time. It should be nice now.

**Comment by Pil0tXia** [comment]
> Please add `pinned` tag for #3873 and #888. Thanks.
> 
> Here is the list of issues included in #3873 that are still unclaimed at this time, please add `help wanted` tag to keep them:
> 
> * [ ]  [[Feature] Realize the source/sink connector #3804](https://github.com/apache/eventmesh/issues/3804)
> * [ ]  [[Feature] Integerate EventMesh into k8s #3327](https://github.com/apache/eventmesh/issues/3327)
> * [ ]  [[Enhancement][WIP]EventMesh integrates OpenFunction as its Async Framework proposal  #2040](https://github.com/apache/eventmesh/issues/2040)
> * [ ]  [[Enhancement] Workflow Feature Implementation: Extended task types to support function orchestration #2187](https://github.com/apache/eventmesh/issues/2187)
> * [ ]  [[Feature] Integration with openSergo as EDA governance implementation #2805](https://github.com/apache/eventmesh/issues/2805)
> * [ ]  [[Feature] Event Streaming #676](https://github.com/apache/eventmesh/issues/676)
> 
> Besides, maybe you would like to add this issue into `What are we doing now?`: #2179

PTAL~ 😉 @xwm1992 @lrhkobe

**Comment by Pil0tXia** [comment]
Change log:
- Never close a PR
- Stale PR message encourages communication
- Close timer after stale message extended to 14 days

**Comment by Pil0tXia** [comment]
@xwm1992 @pandaapo @mxsm 

I have updated this action. Now, the Stale Bot will not close any issues or pull requests. I prefer to have it simply provide reminders and guide contributors on how to advance their work with the help of the community.

In my opinion, the most effective way for reviewers to use the Stale Bot is to combine it with the mailing list. Comments sent by the Stale Bot in the issue@eventmesh.apache.org can be archived into a dedicated folder. Whenever this folder receives a new email, reviewers can check the corresponding pull request to see the progress.

I have added exclusion labels for issues that do not require comments from the Stale Bot.

Let me know your thoughts on this.

---

The Stale Issue message:

It has been 90 days since the last activity on this issue. Apache EventMesh values the voices of the community. Please don't hesitate to share your latest insights on this matter at any time, as the community is more than willing to engage in discussions regarding the development and optimization directions of this feature.

If you feel that your issue has been resolved, please feel free to close it. Should you have any additional information to share, you are welcome to reopen this issue.

---

The Stale PR message:

It has been 60 days since the last activity on this pull request. I am reaching out here to gently remind you that the Apache EventMesh community values every pull request, and please feel free to get in touch with the reviewers at any time. They are available to assist you in advancing the progress of your pull request and offering the latest feedback.

If you encounter any challenges during development, seeking support within the community is encouraged. We sincerely appreciate your contributions to Apache EventMesh.

---

For the parameter `days-before-pr-stale: 60`, I set it to 60 because, apart from Dependabot's PR, there were 19 inactive PRs in the past 90 days, 20 inactive PRs in the past 60 days, and 21 inactive PRs in the past 30 days. Therefore, I feel that 60 is a reasonable value.

| Days Before Issue Stale                   | Number of Inactive PRs                  |
|-----------------------------|------------------------|
| 90       | 19                     |
| 60       | 20                     |
| 30       | 21                     |

For the parameter `days-before-issue-stale: 90`, I feel that 90 is a reasonable value:

| Days Before Issue Stale  | Number of Inactive Issues |
|--------------------------|---------------------------|
| 120                      | 152                       |
| 90                       | 155                       |
| 60                       | 160                       |
| 30                       | 174                       |

**Review by xwm1992 — APPROVED** [review]
LGTM

**Review by mxsm — APPROVED** [review]
LGTM

**Comment by Pil0tXia** [comment]
@xwm1992 Would you please kindly re-approve it

**Review by xwm1992 — APPROVED** [review]

**Pull request merged**
