### PR TITLE
[WIP][ISSUE #4043]initial implementation of filter and transform

### PR DESCRIPTION
**Pull request by pmupkin**
Initial Informal Implementation of Filter and Transform. Link to relevant issues: #825 . #4043 . #3263
## **1. Overview**

Filter and transformer are components of EventMesh used for event filtering and event transformation. During the process of sending and receiving events in EventMesh, rules for event filtering and transformation can be configured to achieve the capability of filtering and transforming events.

Filter refers to the process of filtering events in event subscriptions using configured filtering rules, and then routing the filtered events to event destinations.

Transformer refers to the process of transforming the content of events by configuring types in event subscriptions, converting CloudEvents standard events into event types that event destinations can accept.

Both of these functionalities are implemented using Jackson and JsonPath.

## **Filter**

Filter is an event filtering module. Its primary function is to match events generated by the event source with filtering rules. Only when a successful match occurs, the event will be routed to the event destination associated with the filtering rule. The filtering rule must have the same structure as the matched event.

1. Supported filtering conditions:
    - **Prefix Match**: Specifies matching based on the value of a particular field with a prefix. The keyword is **`prefix`**.
    - **Anything-But Match**: Specifies matching a string-type field with any value except the ones provided. The keyword is **`anything-but`**.
    - **Suffix Match**: Specifies matching based on the value of a particular field with a suffix. The keyword is **`suffix`**.
    - **Numeric Match**: Specifies matching within a range of numeric values. You need to specify an operator and a number, with operators including ">" (greater than), ">=" (greater than or equal to), "<=" (less than or equal to), "<" (less than), "=" (equal to), and "!=" (not equal to). Numeric values are treated as Doubles by default and should be stored in an array format. The keyword is **`numeric`**.
    - **Existence Match**: Checks whether a field exists, with options to set it as true if it exists or false if it doesn't. The keyword is **`exists`**.
    - **Specified Match**: Determines whether a value exists in a particular field. In this type of matching condition, there's no need to specify a value.
    - **Composite Match**: In addition to individual matching rules, Filter also supports combining multiple rules to create more complex event patterns.
    
    Matching between different fields is performed using AND logic, while matching within the same field is performed using OR logic by default.

2. Processing Flow

The implementation of the filter primarily relies on patterns and conditions. The execution flow of the filter is illustrated in the diagram below:
未命名文件 (11)

PatternBuilder: Responsible for parsing the condition content and generating patterns.

Pattern: Evaluates events based on filtering conditions and returns results.

ConditionBuilder: Constructs specific conditions based on different condition keywords.

Condition: Includes various matching conditions, each with its own matching implementation.

3. Usage Example
```java
String condition = "{
    "source":[
        {
            "prefix":"eventmesh."
        },
				{
            "suffix":"eventmesh."
        },
    ]
}";
String event = "{
  "id": "7bf73129-1428-4cd3-a780-95db273d1602",
  "source": "eventmesh.source",
  "time": "2023-11-11T21:29:54Z",
  "data":{
        "name":"filter-test",
        "example":"demo"
    }
}";
Pattern pattern =  PatternBuilder.build(condition);
Boolean res = pattern.filter(cont);
```

## **Transformer**
The transformer is an event conversion module designed to transform CloudEvents standard events into types that the event target can process.

1. Supported Types

Transformer supports three types of transformations:

Direct Transfer: No event transformation is performed; the CloudEvents standard event is directly routed to the target.

Constant: Regardless of the event content, the event triggers the event target without sending the event content to the target.

Variable: Extract variable values from the CloudEvents standard event and route them to the event target according to the format defined in the template. Users can define custom templates and specify the list of variables to extract. The transformer will extract the variables from the event and route them to the event target according to the template's defined format.

2. Processing Flow

As an example of template matching in the transformer, the implementation is as follows:
未命名文件 (12)

3. Usage Example
```java
//ORIGIN
Transformer transformer =new TransformerBuilder.Builder(TransformerType.ORIGINAL).build();
String output = transformer.transform(EVENT);
//Constant
Transformer transformer = new TransformerBuilder.Builder(TransformerType.CONSTANT).setContent("constant test").build();
String output = transformer.transform(EVENT);

```

### CODE REVIEW

**Review by mxsm — COMMENTED** [review]
@pmupkin  Please link this pr to related issue

**Comment by Alonexc** [comment]
image
please check code style.

**Comment by pmupkin** [comment]
> image please check code style.
 Sure, I have fixed the code style issues.

**Comment by pmupkin** [comment]
> @pmupkin Please link this pr to related issue

Okay, I've added some explanations and clarifications, and I've also re-linked the related issues.

**Review by xwm1992 — APPROVED** [review]

**Review by lrhkobe — APPROVED** [review]
LGTM

**Pull request merged**
