### PR TITLE
[ISSUE #4690] Fix Kafka Connector failed to start

### LINKED ISSUE #4690: [Bug] Kafka Connector failed to start
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Environment

Windows

### EventMesh version

master

### What happened

Kafka Connector failed to start since https://github.com/apache/eventmesh/pull/4180.

### How to reproduce

run KafkaConnectServer.

It seems to be the problem of `org.apache.eventmesh.connector.kafka.sink.config.SourceConnectorConfig#keyConverter`.

### Debug logs

```
2023-12-27 15:55:46,176 ERROR [main] Application(Application.java:59) - connector kafkaSource initialize error
org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:823) ~[kafka-clients-3.0.0.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:664) ~[kafka-clients-3.0.0.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:645) ~[kafka-clients-3.0.0.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:625) ~[kafka-clients-3.0.0.jar:?]
	at org.apache.eventmesh.connector.kafka.source.connector.KafkaSourceConnector.init(KafkaSourceConnector.java:66) ~[classes/:?]
	at org.apache.eventmesh.openconnect.Application.run(Application.java:56) [classes/:?]
	at org.apache.eventmesh.connector.kafka.server.KafkaConnectServer.main(KafkaConnectServer.java:38) [classes/:?]
Caused by: org.apache.kafka.common.KafkaException: class org.apache.kafka.common.serialization.StringSerializer is not an instance of org.apache.kafka.common.serialization.Deserializer
	at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstance(AbstractConfig.java:403) ~[kafka-clients-3.0.0.jar:?]
	at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstance(AbstractConfig.java:434) ~[kafka-clients-3.0.0.jar:?]
	at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstance(AbstractConfig.java:419) ~[kafka-clients-3.0.0.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:708) ~[kafka-clients-3.0.0.jar:?]
	... 6 more
```

image

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

### PR DESCRIPTION
**Pull request by Pil0tXia**
Fixes #4690.

### Motivation

#4690

### Modifications

1. Fix `Failed to construct kafka consumer` error
2. Fix `The session timeout is not within the range allowed by the broker` error happened after the previous fix
3. Fix wrong default bootstrap server port
4. ~~Increase `master` branch version from `1.9.0-release` to `1.10.0-release`~~
5. ~~Add new versions for bug issue template~~ and remove redundant line-breaks
6. Fix an operator log typo

### Documentation

- Does this pull request introduce a new feature? (no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
- If a feature is not applicable for documentation, explain why?
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by mxsm** [comment]
@Pil0tXia Can I create a separate pull request to address the version issue? It's recommended to handle one thing per pull request for better clarity.

**Comment by xwm1992** [comment]
> @Pil0tXia Can I create a separate pull request to address the version issue? It's recommended to handle one thing per pull request for better clarity.

I agree this approach, each PR should not include too many changes that are not related to the PR theme.

**Comment by Pil0tXia** [comment]
@mxsm @xwm1992 No problem, I will remove changes of version.

**Review by xwm1992 — APPROVED** [review]

**Review by mxsm — APPROVED** [review]
LGTM

**Pull request merged**
