### PR TITLE
[ISSUE #3926]checkStyle.xml can not check the file header

### LINKED ISSUE #3926: [Enhancement] checkStyle.xml can not check the file header
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

checkStyle.xml can not check the file header.

### Describe the solution you'd like

Enable checkstyle.xml to check the file header.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by pandaapo**
Fixes #3926.

### Motivation

checkStyle.xml can not check the file header.

### Modifications

Enable checkstyle.xml to check the file header.

### Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
- If a feature is not applicable for documentation, explain why?
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Review by Alonexc — APPROVED** [review]
LGTM

**Review by xwm1992 — APPROVED** [review]

**Review by lrhkobe — APPROVED** [review]
LGTM

**Comment by pandaapo** [comment]
@xwm1992 Do you need me to fix the errors in CI?

**Comment by xwm1992** [comment]
> @xwm1992 Do you need me to fix the errors in CI?

It's ok.

**Pull request merged**
