### PR TITLE
[ISSUE#3834] Repeat the operation using method instead.

### LINKED ISSUE #3834: [Enhancement] Repeat the operation using method instead.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

image
located at:
eventmesh-protocol-plugin/eventmesh-protocol-meshmessage/src/main/java/org/apache/eventmesh/protocol/meshmessage/resolver/grpc/GrpcMessageProtocolResolver.java line 225-244

### Describe the solution you'd like

image
image

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by nikam14**
Fixes #3834 .

### Motivation

Optimisation.

### Modifications

made a method .
removed repeated function call.
used method .

### Documentation

- Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Review by Alonexc — DISMISSED** [review]
LGTM

**Review by mxsm — APPROVED** [review]
LGTM~

**Comment by Alonexc** [comment]
image
please check ckeckstyle.

**Comment by nikam14** [comment]
sorry, I can't fix it right now may be later

**Comment by harshithasudhakar** [comment]
@nikam14 Are you still working on this issue?

**Comment by Pil0tXia** [comment]
Hi @nikam14 , the issue has been closed because ternary operations existed in EventMesh are few now and there's no need for an addtional utility method. Do you have any additional information to share? Feel free to share your latest insights with us. If you feel that your issue has been resolved, you are welcome to close it. We sincerely appreciate your contributions to Apache EventMesh.

**Pull request closed without merging**
