### PR TITLE
[ISSUE #3827] Changed Access Modifiers for MessageQueue items

### LINKED ISSUE #3827: [Enhancement] Do some code optimization.[MessageQueue]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

image
image
image
located at:
eventmesh-storage-plugin/eventmesh-storage-standalone/src/main/java/org/apache/eventmesh/storage/standalone/broker/MessageQueue.java line 32,68,87,105,129,152,178,
eventmesh-storage-plugin/eventmesh-storage-standalone/src/test/java/org/apache/eventmesh/storage/standalone/broker/MessageQueueTest.java line 46,53,60,67,74,81,94
analysis and explanation:
a. Public class variable fields do not respect the encapsulation principle and has three main disadvantages:
Additional behavior such as validation cannot be added.
The internal representation is exposed, and cannot be changed afterwards.
Member values are subject to change from anywhere in the code and may not meet the programmer’s assumptions.
By using private attributes and accessor methods (set and get), unauthorized modifications are prevented.
b. Overriding or shadowing a variable declared in an outer scope can strongly impact the readability, and therefore the maintainability, of a piece of code. Further, it could lead maintainers to introduce bugs because they think they’re using one variable but are really using another.

### Describe the solution you'd like

a. Change to use the private final modifier.
image
image
image

b. 'lock' rename.
image

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by Ishaan29**
Fixes #3827 .

### Motivation

the issue explains 
a. Public class variable fields do not respect the encapsulation principle and has three main disadvantages:
Additional behavior such as validation cannot be added.
The internal representation is exposed, and cannot be changed afterwards.
Member values are subject to change from anywhere in the code and may not meet the programmer’s assumptions.
By using private attributes and accessor methods (set and get), unauthorized modifications are prevented.
b. Overriding or shadowing a variable declared in an outer scope can strongly impact the readability, and therefore the maintainability, of a piece of code. Further, it could lead maintainers to introduce bugs because they think they’re using one variable but are really using another.

### Modifications

- Changed Access modifier of `items[]`
- Added getters for the same
- Changed Breaking tests
-  Renamed Method scoped to `reentrantLock`

### Documentation

- Does this pull request introduce a new feature? (yes / no) no
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
- If a feature is not applicable for documentation, explain why? Refactoring and Optimization
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by Ishaan29** [comment]
hey @mxsm @Alonexc 

could you please review this ?

thanks in advance

**Comment by Alonexc** [comment]
These errors don't appear to be related to your pr submission, but they have been fixed.

**Review by Alonexc — APPROVED** [review]
LGTM

**Comment by xwm1992** [comment]
@Ishaan29 please merge the latest master branch code to your pr, to fix the ci check error.

**Review by lrhkobe — APPROVED** [review]

**Review by xwm1992 — APPROVED** [review]

**Pull request merged**
