### PR TITLE
[ISSUE #4521] A poor naming.

### LINKED ISSUE #4521: [Enhancement] A poor naming.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

https://github.com/apache/eventmesh/blob/11def17e8bd41c9ff5180926cfdac9aa020af18e/eventmesh-admin/src/main/java/org/apache/eventmesh/admin/enums/Errors.java#L36-L38

A class that defines multiple response states, including `SUCCESS` state, but the class name is `Errors`. Bad smell should be avoided in our codes. Because it will reduce code's readability and maintainability, and also confuse developers.

### Describe the solution you'd like

Change the class name to an appropriate name.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

### PR DESCRIPTION
**Pull request by Asymtode712**
Fixes #4521 

### Motivation

*Explain the content here.*
*Explain why you want to make the changes and what problem you're trying to solve.*

### Modifications

*Describe the modifications you've done.*

### Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
- If a feature is not applicable for documentation, explain why?
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by Asymtode712** [comment]
@pandaapo Please review my PR and suggest changes if there exists any.

**Comment by Pil0tXia** [comment]
Duplicate with https://github.com/apache/eventmesh/issues/4501. 

https://github.com/Pil0tXia/eventmesh/blob/pil0txia_feat_4501/eventmesh-admin/src/main/java/org/apache/eventmesh/admin/enums/Status.java

**Comment by Asymtode712** [comment]
As my old commit PR was being tagged Duplicate by @Pil0tXia. I have changed the class name to 'Test'.
My new commit is all free from any duplication from any previous PRs.
@pandaapo Kindly take a look at it

**Comment by Asymtode712** [comment]
@pandaapo i used the class name 'Status' in my last commit with was tagged as Duplicate by @Pil0tXia. If you allow me i can rollback to the previous version of the commit.

**Comment by Asymtode712** [comment]
Am i allowed to do it @pandaapo ?

**Comment by Pil0tXia** [comment]
The usage of this exception enumeration class has already undergone some changes in my development branch. Renaming it based on the existing master branch would make it difficult to merge my branch. If you want this issue to be fixed as soon as possible, I can submit a portion of the code first. If you're not in a hurry, you can see these changes in PR #4501. @pandaapo 

---

这个异常枚举类的用法在我的开发分支中已经发生了一些改变，根据现有的master分支进行重命名，会导致我的分支合入困难。如果您希望这个问题被尽快修复，我可以先提交一部分代码。如果您不着急的话，您会在 #4501 的PR中见到这些更改。

**Comment by Asymtode712** [comment]
@pandaapo I have done all the changes. Please review my PR

**Comment by Pil0tXia** [comment]
@Asymtode712 Hi, welcome. I'm sorry, but the changes you're making conflict significantly with my development work. You might want to consider working on a different good first issue. Additionally, editing code in this way using GitHub's online editor is not recommended. It's better to use an IDE that supports the Java language for code refactoring.

**Comment by Asymtode712** [comment]
@Pil0tXia I have discovered all the occurences using VS Code only. I have just replaced them using Github's editor.

**Comment by Pil0tXia** [comment]
@Asymtode712 I'm sorry that this PR doesn't correspond with EventMeshAdmin's development plan and it conflicts a lot. I'm the author of `eventmesh-admin` and this module is under active development. If you can try another good first issue, I'd be happy to review it for you. Again, my apologies.

**Comment by Asymtode712** [comment]
Apologies @Pil0tXia, but i would like to hear from @pandaapo once

**Pull request closed without merging**
