### PR TITLE
[ISSUE #3407] Make this anonymous inner class a lambda[SendSyncMessageProcessor]

### LINKED ISSUE #3407: [Enhancement] Make this anonymous inner class a lambda[SendSyncMessageProcessor]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

image
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendSyncMessageProcessor.java line 260
analysis and explanation:
Before Java 8, the only way to partially support closures in Java was by using anonymous inner classes. But the syntax of anonymous classes may seem unwieldy and unclear.
With Java 8, most uses of anonymous inner classes should be replaced by lambdas to highly increase the readability of the source code.

### Describe the solution you'd like

image

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by Sunstreaker**
Fixes #3407

### Motivation

*Enhancement.*

### Modifications

*Code refactor from anonymous inner class a lambda[SendSyncMessageProcessor].*

### Documentation

- Does this pull request introduce a new feature? (no)
- If yes, how is the feature documented? (not applicable)
- If a feature is not applicable for documentation, explain why? - Code refactor

### CODE REVIEW

**Comment by Sunstreaker** [comment]
@Alonexc  Please review and help me in merging the PR !

**Review by Alonexc — APPROVED** [review]
LGTM

**Comment by Sunstreaker** [comment]
@Alonexc possible to merge this?

**Comment by Alonexc** [comment]
Of course, please wait, I don't have permission.

**Comment by mroccyen** [comment]
Please resolve conflicts

**Review by xwm1992 — APPROVED** [review]

**Pull request merged**
