### PR TITLE
[ISSUE #4540] [Unit Test] Unit test for ThreadUtils #4540

### LINKED ISSUE #4540: [Unit Test] Unit test for ThreadUtils
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Read the unit testing guidelines

- [X] I have read.

### Unit test request

Add Unit Test for ThreadUtils.java

### Describe the unit tests you want to do

Module name: eventmesh-common
Located at: [eventmesh](https://github.com/apache/eventmesh/tree/master)/[eventmesh-common](https://github.com/apache/eventmesh/tree/master/eventmesh-common)/[src](https://github.com/apache/eventmesh/tree/master/eventmesh-common/src)/[main](https://github.com/apache/eventmesh/tree/master/eventmesh-common/src/main)/[java](https://github.com/apache/eventmesh/tree/master/eventmesh-common/src/main/java)/[org](https://github.com/apache/eventmesh/tree/master/eventmesh-common/src/main/java/org)/[apache](https://github.com/apache/eventmesh/tree/master/eventmesh-common/src/main/java/org/apache)/[eventmesh](https://github.com/apache/eventmesh/tree/master/eventmesh-common/src/main/java/org/apache/eventmesh)/[common](https://github.com/apache/eventmesh/tree/master/eventmesh-common/src/main/java/org/apache/eventmesh/common)/[utils](https://github.com/apache/eventmesh/tree/master/eventmesh-common/src/main/java/org/apache/eventmesh/common/utils)/[ThreadUtils.java](https://github.com/apache/eventmesh/blob/master/eventmesh-common/src/main/java/org/apache/eventmesh/common/utils/ThreadUtils.java)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by VishalMCF**
Fixes #4540

### Motivation

*Explain the content here.*
*Explain why you want to make the changes and what problem you're trying to solve.*

### Modifications

*Describe the modifications you've done.*

### Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
- If a feature is not applicable for documentation, explain why?
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by Pil0tXia** [comment]
Kindly refer to the standard title format used in other PRs.

**Comment by Pil0tXia** [comment]
plz check ci~

**Comment by Pil0tXia** [comment]
@VishalMCF Please check CI failure.

**Comment by VishalMCF** [comment]
@Pil0tXia I ran the checkstyle plugin. But the file which i worked on is now fixed as per the results. But there is another file -> Execution failed for task ':eventmesh-protocol-plugin:eventmesh-protocol-grpc:generateProto'.
> protoc: stdout: . stderr: /Users/vishalyadav/.gradle/caches/modules-2/files-2.1/io.grpc/protoc-gen-grpc-java/1.43.2/d1f6199ad60848a873bd14fc8deefc6733b75586/protoc-gen-grpc-java-1.43.2-osx-aarch_64.exe: program not found or is not executable
  Please specify a program using absolute path or make sure the program is available in your PATH system variable
  --grpc_out: protoc-gen-grpc: Plugin failed with status code 1.
  
  This is failing.

**Comment by Pil0tXia** [comment]
@VishalMCF 

I re-ran the failed task of CI and it is still failing.

image

May you please check [debug log](https://github.com/apache/eventmesh/actions/runs/8680910282/job/23812602913?pr=4818) for detailed information?

---

The log you reported about ':eventmesh-protocol-plugin:eventmesh-protocol-grpc:generateProto' seems to be a dependency installation problem.

**Comment by VishalMCF** [comment]
@Pil0tXia I checked it is failing because of the randomized test case. Its failing during build. ALthough on my local machine it passes.

**Comment by Pil0tXia** [comment]
>failing because of the randomized test case

You can absolutely make changes to other test cases.

**Pull request closed without merging**
