### PR TITLE
[ISSUE #4788] Support disruptor as memory queue

### PR DESCRIPTION
**Pull request by jevinjiang**
Fixes https://github.com/apache/eventmesh/issues/4788

Motivation
 Support disruptor as memory queue https://github.com/apache/eventmesh/issues/4788

Documentation
- Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Review by xwm1992 — APPROVED** [review]
LGTM

**Comment by jevinjiang** [comment]
do i need to do something？

**Review by Pil0tXia — APPROVED** [review]

**Comment by Pil0tXia** [comment]
Closing and will reopen to re-run CI.

**Comment by Pil0tXia** [comment]
@jevinjiang Merged. Sorry for the lengthy review cycle on this PR.

**Comment by jevinjiang** [comment]
@Pil0tXia  No problem. I was a bit busy recently, but I will continue to contribute

**Pull request merged**
