### PR TITLE
[ISSUE #4268] Use switch to replace the if-else.[CloudEventsProtocolAdaptor]

### LINKED ISSUE #4268: [Enhancement] Use switch to replace the if-else.[CloudEventsProtocolAdaptor]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

image
image
located at:
eventmesh-protocol-plugin/eventmesh-protocol-cloudevents/src/main/java/org/apache/eventmesh/protocol/cloudevents/CloudEventsProtocolAdaptor.java line 92-102,120-150

### Describe the solution you'd like

image
image

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by hanshal101**
Fixes  #4268 

### Motivation

This PR solves the issue #4628
*[Enhancement] Use switch to replace the if-else.[CloudEventsProtocolAdaptor] #4268*

### Modifications

Replaced the if-else statements on line 92-102 & 120-150 with switch cases.

### Documentation

- Does this pull request introduce a new feature?
-  (no)
- If yes, how is the feature documented? 
- (not applicable)
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation. 
- (not required)

### CODE REVIEW

**Review by mxsm — COMMENTED** [review]
@hanshal101  Please check code style
image

**Comment by hanshal101** [comment]
I'll look at this issue

**Comment by hanshal101** [comment]
Heyy @mxsm, here the enum values are not constant expression. We can solve this issue by two methods
1) Keeping the if-else statement
2) Using switch cases but also making the 'public enum RequestCode{ }' object

What would you prefer and please do share your thoughts on this.

**Comment by silentchildh** [comment]
> Heyy @mxsm, here the enum values are not constant expression. We can solve this issue by two methods
> 
> 1. Keeping the if-else statement
> 2. Using switch cases but also making the 'public enum RequestCode{ }' object
> 
> What would you prefer and please do share your thoughts on this.

In `RequestCode`  already has ` public static RequestCode get(Integer requestCode)` method, so you can consider to use it.

**Review by mxsm — COMMENTED** [review]
@hanshal101 this issue has been fixed, I will close this pr

**Pull request closed without merging**
