### PR TITLE
[ISSUE #4088] Anonymous new can be replaced with lambda.[BroadCastSubClient]

### LINKED ISSUE #4088: [Enhancement] Anonymous new can be replaced with lambda.[BroadCastSubClient]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

image
located at:
eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/demo/BroadCastSubClient.java line 43,50

### Describe the solution you'd like

replace with lambda. use the correct log format.
image

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by Monika-Sivakumar-3**
Replace with lambda

Fixes #4088 .

### Motivation

*Replacing with lambda*

### Modifications

*Replacing a function with lambda*

### Documentation

- Does this pull request introduce a new feature? No
- If yes, how is the feature documented? Not applicable
- If a feature is not applicable for documentation, explain why? Not applicable

### CODE REVIEW

**Review by mxsm — APPROVED** [review]
LGTM

**Review by Pil0tXia — APPROVED** [review]
LGTM. Please use the standard format for PR title by the way.

**Comment by Alonexc** [comment]
Current pr seems to duplicate pr[ #4469].

**Comment by xwm1992** [comment]
For there is no response, I'll close this pr and let others do this.

**Pull request closed without merging**
