### PR TITLE
[ISSUE #4025] Comparison using reference equality instead of value equality

### LINKED ISSUE #4025: [Enhancement] Comparison using reference equality instead of value equality.[QueryOperationsResponse]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

image
image
located at:
eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/catalog/protos/QueryOperationsResponse.java line 338,484
analysis and explanation:
Reference types that declare an equals() method, or that inherit equals() from a type other than Object, should not be compared for reference equality with == or !=. Instead, always compare for value equality with .equals().

### Describe the solution you'd like

change to use equals() to compare.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by AbhishekPSingh07**
Fixes #4025 .

### Motivation

*Explain the content here.*
*Explain why you want to make the changes and what problem you're trying to solve.*

### Modifications

*Describe the modifications you've done.*

### Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
- If a feature is not applicable for documentation, explain why?
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Review by Pil0tXia — APPROVED** [review]

**Review by xwm1992 — APPROVED** [review]

**Review by mxsm — APPROVED** [review]
LGTM

**Comment by AbhishekPSingh07** [comment]
Hey @xwm1992 @mxsm @Pil0tXia. I am new to open-source projects. I have contributed to small projects and am confident in Java language could you please refer me some resources so that I can understand and contribute more to this repo.

**Comment by Pil0tXia** [comment]
@AbhishekPSingh07 Thank you for your contribution. The message retry logics are currently separated in each protocol (such as `org.apache.eventmesh.runtime.core.protocol.http.retry.HttpRetryer`), and you may abstract them if you are interested.

You may refer to these two PR and collaborate with them:
https://github.com/apache/eventmesh/pull/4061
https://github.com/apache/eventmesh/pull/4179

**Comment by AbhishekPSingh07** [comment]
ok will give it a go

**Pull request merged**
