### PR TITLE
[ISSUE #4254] Every utility class should be annotated with @UtilityClass as we are using lombok

### LINKED ISSUE #4254: [Enhancement] Every utility class should be annotated with @UtilityClass as we are using lombok
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

Every utility class should be refactored with `@UtilityClass` annotation as we are using lombok.
What do you think about this refactoring?

### Describe the solution you'd like

Annotate all utility classes with `@UtilityClass`

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by harshithasudhakar**
Fixes #4254 

### Motivation

Every utility class should be refactored with `@UtilityClass` annotation as we are using lombok.

### Modifications

Annotated all utility classes with `@UtilityClass`

### Documentation

- Does this pull request introduce a new feature? (yes/no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
- If a feature is not applicable for documentation, explain why?
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Review by HattoriHenzo — COMMENTED** [review]
@harshithasudhakar there are other classes that can be annotated with `@UtilityClass` annotation

**Comment by harshithasudhakar** [comment]
> @harshithasudhakar
> 
> * there are other classes that can be annotated with `@UtilityClass` annotation
> * also you can this refactoring in one pull request
> * no need to name your branch with **patch** in the name. This is not really a patch, but a code refactoring. _eventmesh-#issuenumber_ is also a good choice to start with.

Sure, I'll make a PR soon accordingly

**Comment by harshithasudhakar** [comment]
If we annotate `@UtilityClass` for this class then the constructor `UrlMappingPattern()` will be flagged as an error by the private constructor automatically generated by lombok. So, do we just leave this class as it was?

**Comment by HattoriHenzo** [comment]
@harshithasudhakar yes you can leave this class for the moment, the `@UtilityClass` annotation is not applicable to all classes.

**Comment by Pil0tXia** [comment]
Would delete this unmerged `harshithasudhakar-patch-1` branch because its work has been superseded with https://github.com/apache/eventmesh/pull/4382.

**Pull request closed without merging**
