### PR TITLE
[ISSUE #4191] Do some code optimization.[StreamPushRequest]

### LINKED ISSUE #4191: [Enhancement] Do some code optimization.[StreamPushRequest]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

image
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/push/StreamPushRequest.java line 104-111,115-122

### Describe the solution you'd like

a. repeat code extraction as a method
b. use switch instead.
image
image

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by himansh295**
Fixes #4191.

### Motivation

*Explain the content here.*
*Explain why you want to make the changes and what problem you're trying to solve.*

### Modifications

*Describe the modifications you've done.*

### Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
- If a feature is not applicable for documentation, explain why?
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by harshithasudhakar** [comment]
@himansh295 Please standardize your PR title and `Fixes`, also resolve the merge conflicts.

**Review by mxsm — CHANGES_REQUESTED** [review]
@himansh295   Has conflicts that must be resolved

**Comment by himansh295** [comment]
@mxsm Update the PR with the pull of latest master

**Comment by mxsm** [comment]
> @mxsm Updated the PR with the pull of the latest master.Please check again

@himansh295  you can rebase or merge master and fix conflicts, Then submit agagin

**Comment by himansh295** [comment]
Please check for the new PR for the same issue I have created. Making this PR close.
@mxsm .
PR -https://github.com/apache/eventmesh/pull/4356

**Pull request closed without merging**
