### PR TITLE
[ISSUE #4991] add unit test for LogUtil

### PR DESCRIPTION
**Pull request by melisolmez**
Fixes https://github.com/apache/eventmesh/issues/4991

Motivation
Increase test coverage

Modifications
Added new tests for LogUtil.java located https://github.com/apache/eventmesh/blob/master/eventmesh-common/src/main/java/org/apache/eventmesh/common/utils/LogUtilTest.java

Documentation
Does this pull request introduce a new feature? (no)
If yes, how is the feature documented? (not applicable)
If a feature is not applicable for documentation, explain why?
If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Review by harshithasudhakar — APPROVED** [review]

**Comment by harshithasudhakar** [comment]
Hi, please resolve the failing CI errors. To resolve the issue, you can view the test report generated during the build.

**Comment by melisolmez** [comment]
hello @harshithasudhakar, I tried solve this problem but I cannot understand. There were failing tests. See the report at: file:///Users/runner/work/eventmesh/eventmesh/eventmesh-common/build/reports/tests/test/index.html  when I saw this location but there is not fail test in index.html. Could you help with this problem?

**Comment by harshithasudhakar** [comment]
I re-ran the log, it has passed :)

**Comment by melisolmez** [comment]
@harshithasudhakar Hello, I want to close this PR. I need someone else to accept it. Can you help me?

**Review by Pil0tXia — APPROVED** [review]

**Comment by Pil0tXia** [comment]
good job

**Pull request merged**
