### PR TITLE
[ISSUE #3521] Swapped the actual and expected values

### PR DESCRIPTION
**Pull request by bsh786**
### Modifications
 Modified the assertEquals method which was earlier in the form of Assert.assertEquals(actual, expected) to be in the 
 correct order which is Assert.assertEquals(expected, actual).

### Documentation

- Does this pull request introduce a new feature? (yes / no)
   No
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
- If a feature is not applicable for documentation, explain why?
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Review by mxsm — COMMENTED** [review]
Hi @bsh786  CI not pass, please fix it

**Comment by Alonexc** [comment]
Fixed #3521

**Comment by Alonexc** [comment]
image
Please check the checkstyle.

**Comment by bsh786** [comment]
Hi @mxsm , @Alonexc,

I've made the changes. Pls check and approve.

Thanks

**Review by mxsm — APPROVED** [review]
LGTM~

**Review by mytang0 — APPROVED** [review]

**Pull request merged**
