### PR TITLE
Added tests for OpenFunctionSinkConnector

### LINKED ISSUE #4548: [Unit Test] Add unit test for OpenFunctionSinkConnector.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Read the unit testing guidelines

- [X] I have read.

### Unit test request

Add unit test for OpenFunctionSinkConnector.

### Describe the unit tests you want to do

Add unit test for OpenFunctionSinkConnector.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by VishalMCF**
Fixes #4548

### Motivation

OpenFunctionSinkConnector did not have any test cases.

### Modifications

A new class called OpenFunctionSinkConnectorTest was added with two test cases.

### Documentation

- Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Comment by VishalMCF** [comment]
@pandaapo please review

**Comment by VishalMCF** [comment]
yeah missed that. WIll do it ASAP

**Comment by VishalMCF** [comment]
@Pil0tXia Can you please review?

**Review by Pil0tXia — APPROVED** [review]
LGTM

**Review by mxsm — APPROVED** [review]

**Pull request merged**
