### PR TITLE
[ISSUE #4243] Optimize Webhook Manufacturer source Hard-coding

### LINKED ISSUE #4243: [Enhancement] Optimize Webhook Manufacturer source Hard-coding
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

image

Some webhook manufacturer's domain name may not follow the `www.example.com` format with a `www` subdomain and a `.com` TLD.

### Describe the solution you'd like

Add manufacturerDomain field or try some other solution.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by Pil0tXia**
Fixes #4243.

### Motivation

image

Some webhook manufacturers' domain names may not follow the `www.example.com` format with a `www` subdomain and a `.com` TLD.

### Modifications

Added `manufacturerDomain` field for `WebHookConfig`.

Validation of this field has been added to the test classes.

Removed redundant `cloudEventSource` field because it shouldn't belong to the WebHook Config entity.

Another hardcoding in `WebHookProcessor` is now replaced by constant.

### Documentation

- Does this pull request introduce a new feature? (no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
- If a feature is not applicable for documentation, explain why?
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Review by mxsm — DISMISSED** [review]
LGTM

**Comment by Pil0tXia** [comment]
@pandaapo Thank you for your attention.
1. The roles of `cloudEventSource` and `manufacturerDomain` are the same.
2. The properties defined within `WebHookConfig` should be related to Webhook configurations. **The variable names defined in this file will be exposed to users as JSON parameters.** The variable naming for `manufacturerDomain` and `manufacturerName` is chosen to intuitively indicate the type of values these fields should accept. However, cloudEventSource is an internal concept of the EventMesh and should not be exposed to users or require them to **speculate about its meaning**, especially in the absence of documentation.
3. In fact, `cloudEventSource` currently serves no purpose and has been deprecated for a long time. The method that should actually call it uses hardcoding (which has been fixed in this PR), and even the test classes incorrectly assign values to it. This indicates that, apart from its definer, no one knows how to use it. This is also one of the reasons for my proposed name modification.

**Comment by xwm1992** [comment]
@Pil0tXia For this pull request modification, you need to take a look at github webhook usage guide https://eventmesh.apache.org/zh/docs/design-document/webhook, ensuring that the new modification does not affect the normal use of the original function.

**Comment by Pil0tXia** [comment]
@xwm1992 Yes, I tested. Modifications made in this PR doesn't affect the process logic or the return value of `getCloudEventSource`.

In fact, the master branch has a NPE when querying webhook configs and I have found the cause. The documents will be updated too.

image

**Comment by Pil0tXia** [comment]
It's all good. PTAL~ @pandaapo @xwm1992 

image

image

Synchronised modification of documents is included in NPE bugfix: https://github.com/apache/eventmesh-site/pull/110

**Comment by Pil0tXia** [comment]
Merge conflicts resolved.

**Review by Alonexc — APPROVED** [review]

**Review by xwm1992 — APPROVED** [review]

**Review by mxsm — APPROVED** [review]

**Pull request merged**
