### PR TITLE
[ISSUE #4785] Condition check for source worker

### PR DESCRIPTION
**Pull request by manojks1999**
* Fixes the [#4785](https://github.com/apache/eventmesh/issues/4785)
* Minor change in condition as per description.

### CODE REVIEW

**Comment by fabian4** [comment]
Please check the CI (fix the import statement order)
for reference https://eventmesh.apache.org/community/contribute/contribute/#code-style

image

**Comment by manojks1999** [comment]
Changes were made, pls have a look.

**Review by fabian4 — APPROVED** [review]
LGTM

**Review by harshithasudhakar — APPROVED** [review]
LGTM

**Pull request merged**
