### PR TITLE
[ISSUE #4021] Replace LinkedList by ArrayList

### LINKED ISSUE #4021: [Enhancement] Replace LinkedList by ArrayList.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

image
image
located at:
eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/tcp/Subscription.java line 27
eventmesh-protocol-plugin/eventmesh-protocol-meshmessage/src/main/java/org/apache/eventmesh/protocol/meshmessage/resolver/grpc/GrpcMessageProtocolResolver.java line 134
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshGrpcServer.java line 279
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/consumer/ConsumerManager.java line 213
eventmesh-sdks/eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/impl/cloudevent/CloudEventTCPSubClient.java line 59
eventmesh-sdks/eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/impl/eventmeshmessage/EventMeshMessageTCPSubClient.java line 51
analysis and explanation:
It is very rare for LinkedList to out-perform ArrayList or ArrayDeque. Avoid it unless you're willing to invest a lot of time into benchmarking. Caveat: LinkedList supports null elements, but ArrayDeque does not.

### Describe the solution you'd like

replace LinkedList by ArrayList.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by VL-037**
Fixes #4021.

### Motivation

this changes resolves #4021 by replace LinkedList with ArrayList.

### Modifications

`eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/tcp/Subscription.java` line 27.
`eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshGrpcServer.java` line 279
`eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/consumer/ConsumerManager.java` line 213
`eventmesh-sdks/eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/impl/cloudevent/CloudEventTCPSubClient.java` line 59
`eventmesh-sdks/eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/impl/eventmeshmessage/EventMeshMessageTCPSubClient.java` line 51

FILE DOESN'T EXIST:
`eventmesh-protocol-plugin/eventmesh-protocol-meshmessage/src/main/java/org/apache/eventmesh/protocol/meshmessage/resolver/grpc/GrpcMessageProtocolResolver.java`

### Documentation

- Does this pull request introduce a new feature? no
- If yes, how is the feature documented? -
- If a feature is not applicable for documentation, explain why? -
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Review by Alonexc — APPROVED** [review]

**Review by Pil0tXia — CHANGES_REQUESTED** [review]
It seems you didn't push the change `eventmesh-protocol-plugin/eventmesh-protocol-meshmessage/src/main/java/org/apache/eventmesh/protocol/meshmessage/resolver/grpc/GrpcMessageProtocolResolver.java` line 134 which is also requested for editing in the issue.

**Comment by VL-037** [comment]
> It seems you didn't push the change `eventmesh-protocol-plugin/eventmesh-protocol-meshmessage/src/main/java/org/apache/eventmesh/protocol/meshmessage/resolver/grpc/GrpcMessageProtocolResolver.java` line 134 which is also requested for editing in the issue.

I've checked the repo and the file doesn't exist. I will quote this on the PR detail

**Comment by Alonexc** [comment]
Some classes may have been removed due to code updates.

**Comment by Alonexc** [comment]
image
please check checkstyle.

**Review by xwm1992 — APPROVED** [review]

**Review by lrhkobe — APPROVED** [review]

**Pull request merged**
