### PR TITLE
[ISSUE #4146] fix some code to pass checkstyle

### LINKED ISSUE #4146: [Bug] Build failed because of invalid code style
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Environment

Mac

### EventMesh version

master

### What happened

[Bug] Build failed because of invalid code style

### How to reproduce

gradle build

### Debug logs

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by TheR1sing3un**
1. fix some code to pass checkstyle

Closes https://github.com/apache/eventmesh/issues/4146

Fixes #4146

### Motivation

*Explain the content here.*
*Explain why you want to make the changes and what problem you're trying to solve.*

### Modifications

*Describe the modifications you've done.*

### Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
- If a feature is not applicable for documentation, explain why?
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by TheR1sing3un** [comment]
@Alonexc PTAL~

**Comment by Alonexc** [comment]
`CallbackServiceGrpc`this class lacks a license.

**Comment by TheR1sing3un** [comment]
> `CallbackServiceGrpc`this class lacks a license.

done~

**Review by Alonexc — APPROVED** [review]
LGTM

**Review by mxsm — APPROVED** [review]
LGTM

**Review by xwm1992 — APPROVED** [review]

**Review by lrhkobe — APPROVED** [review]

**Pull request merged**
