### PR TITLE
[ISSUE #3933] Fix the tcp port.

### LINKED ISSUE #3933: [Bug] The tcp server port is 10002.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Environment

Windows

### EventMesh version

master

### What happened

image
image

### How to reproduce

The tcp port has been changed to 10002, which should be 10000.

### Debug logs

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by Alonexc**
Fixes #3933.

### Motivation

fix tcp port[10000]
fix connector checkstyle

### Modifications

fix tcp port[10000]
fix connector checkstyle

### Documentation

- Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Comment by xwm1992** [comment]
@Alonexc also need to fix other files such as docker file and rocketmq source/sink connector module.

**Comment by Alonexc** [comment]
I saw that you submitted a pr for fixing, should I fix it again on my side too?

**Review by mxsm — APPROVED** [review]
LGTM

**Comment by xwm1992** [comment]
@Alonexc merge the master branch code to fix the ci check error.

**Review by xwm1992 — APPROVED** [review]

**Review by wqliang — APPROVED** [review]

**Review by lrhkobe — APPROVED** [review]
LGTM

**Pull request merged**
