### PR TITLE
[ISSUE #4128] Add eventmesh-connector-rocketmq module

### LINKED ISSUE #4128: [Enhancement] Add eventmesh-connector-rocketmq module
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

The eventmesh-connector-rocketmq module contains rocketmq-source-connector and rocketmq-sink-connector .

### Describe the solution you'd like

The eventmesh-connector-rocketmq module contains rocketmq-source-connector and rocketmq-sink-connector .

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by xwm1992**
Fixes #4128 .

### Motivation

*Explain the content here.*
*Explain why you want to make the changes and what problem you're trying to solve.*

### Modifications

*Describe the modifications you've done.*

### Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
- If a feature is not applicable for documentation, explain why?
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Review by lrhkobe — APPROVED** [review]
LGTM

**Review by wqliang — APPROVED** [review]

**Review by yiliuchen — APPROVED** [review]

**Comment by yiliuchen** [comment]
LGTM

**Comment by pandaapo** [comment]
Don't we design the source connector and corresponding sink connector as two independent modules anymore?

**Comment by Pil0tXia** [comment]
> Don't we design the source connector and corresponding sink connector as two independent modules anymore?

`sink-connector-rocketmq` and `source-connector-rocketmq` were two independent modules last month, but they were merged recently.

**Pull request merged**
